# Generated by Django 3.0.8 on 2020-07-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice2',
            name='question2',
        ),
        migrations.DeleteModel(
            name='Choice1',
        ),
        migrations.DeleteModel(
            name='Choice2',
        ),
    ]
